server:
  servlet:
    context-path: /newspaper-project
  port: 7055

spring:
  jpa:
    hibernate:
      ddl-auto:none
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/newspaper
    username: root
    password: hung2000
    driver-class-name: com.mysql.cj.jdbc.Driver
  show-sql: true